name: Test and Build
on:
  push:
    branches:
      - master
      - dev
      - 'feature/**'
    paths-ignore:
      - '**.md'
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')" # Skip CI if [skip ci] is passed in the commit.
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v2

      - name: 🟢 Create Conda environment using Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          activate-environment: zt2md
          environment-file: dev-env.yaml
          auto-activate-base: false
          use-mamba: true

      - name: Echo
        run: conda info

      - name: 🐍 Setup Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

      - name: ⚙ Install PyPi packages via Poetry
        run: poetry install

      - name: 🕵️ Run pytest
        run: pytest --cov-report xml:coverage.xml

  release:
    runs-on: ubuntu-latest
    needs: test
    if: "!contains(github.event.head_commit.message, '[skip ci]')" # Skip CI if [skip ci] is passed in the commit.
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v2

      - name: 🟢 Create Conda environment using Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          activate-environment: zt2md
          environment-file: dev-env.yaml
          auto-activate-base: false
          use-mamba: true

      - name: 🐍 Setup Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

      - name: ⚙ Install PyPi packages via Poetry
        run: poetry install

      - name: 📤️ Build and publish to pypi
        uses: JRubics/poetry-publish@v1.9
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_name: "testpypi" # no need when properly set up to publish on PyPI
          repository_url: "https://test.pypi.org/legacy/" # no need when properly set up to publish on PyPI
        if: steps.extract_branch.outputs.branch == 'master'